# Modify name if deploying multiple instances
name = "sub-box"

main = ".open-next/worker.js"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

minify = true

assets = { directory = ".open-next/assets", binding = "ASSETS" }

# [placement]
# mode = "smart"

# Environment variables
# Modify these to use the correct environment variables
[vars]
ADMIN_USERNAME = "gzdiky"
ADMIN_PASSWORD = "Q!W@E#r4t5y6" # Change this to a secure password
JWT_SECRET = "0CF485E79D678A8735212E0186D15978" # Change this to a secure secret key
SESSION_TAG = "0"
SESSION_DURATION = "604800"
DEPLOY_TARGET = "cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "sqlsubbox" # Change this to the name of your D1 database
database_id = "2898dd20-6392-4c9b-b0bc-2ab5237b5667" # wrangler d1 info <YOUR_DATABASE_NAME>

[observability.logs]
enabled = true

# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET"
# bucket_name = "prod-sub-box-next-inc-cache"
